import { useErrorAlchemy } from "../../../crafting/useErrorAlchemy/useErrorAlchemy";

const { craftMysticError } = useErrorAlchemy(
  "ErrorAlchemy",
  "assertDefined-function"
);

export const AssertDefinedFailedError = craftMysticError({
  name: "AssertDefinedFailedError",
  errorCode: "DATA_INTEGRITY_VIOLATION",
  severity: "critical",
  cause: "value was null, undefined or NaN",
});

export function assertDefined<T>(
  value: T | null | undefined
): asserts value is T {
  if (value == null || (typeof value === "number" && isNaN(value))) {
    throw new AssertDefinedFailedError({
      message: "Defined-Assertion failed.",
      payload: { value, type: typeof value },
    });
  }
}
